"""Generate the phase 8 weight-sensitivity sweep, recalibrating at every point.

    python scripts/make_phase8.py

Changing the detector weights (w1,w2,w3) changes the largest ``e.w`` a
single-feature attack can reach - ``w_k`` instead of 1/3 - so holding ``theta_0``
fixed turns a weight sweep into a threshold sweep and measures the wrong thing.
Measured here: the closed-form solution moves ``lam_s`` from 11.0 at uniform
weights to 18.0 when one feature is favoured and 7.0 when one is dropped.

Each weight point therefore appears twice in the sweep: once with
``(lam_s, theta_0)`` re-solved for that weighting, and once at the phase 1
defaults.  The gap between the two surfaces is how much of any apparent weight
sensitivity is really threshold sensitivity.
"""
from __future__ import annotations

import dataclasses
import os
import pathlib
import sys

import numpy as np
import yaml

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from sim.calibrate import calibrate_score, measure_evidence_floor  # noqa: E402
from sim.config import load_config  # noqa: E402
from sim.topology import load_topology  # noqa: E402

BASE = "config/attack_t3_otp.yaml"
CALIB = "config/calibration_net50_OTP.yaml"
OUT = "config/sweep_p8_weights.yaml"
SEEDS = list(range(3, 3 + 10 * 10, 10))

WEIGHTS = [
    (1 / 3, 1 / 3, 1 / 3),                                 # the phase 1 default
    (0.6, 0.2, 0.2), (0.2, 0.6, 0.2), (0.2, 0.2, 0.6),     # one feature favoured
    (0.2, 0.4, 0.4), (0.4, 0.2, 0.4), (0.4, 0.4, 0.2),     # one feature de-weighted
    (0.5, 0.5, 0.0), (0.5, 0.0, 0.5), (0.0, 0.5, 0.5),     # one feature dropped
]


def main() -> int:
    cfg = load_config(BASE, {})
    topo = load_topology(cfg.topology, cfg.noise.qber_base_min,
                         cfg.noise.qber_base_max)
    phi = np.asarray(yaml.safe_load(
        pathlib.Path(CALIB).read_text(encoding="utf-8"))["phi"], dtype=float)

    # the evidence floor is a property of the network and the noise, not of the
    # weighting, so it is measured once
    e_floor = measure_evidence_floor(cfg, phi)
    print("evidence floor:", e_floor.round(4).tolist())
    print(f"\n  {'weights':>22}{'lam_s':>8}{'theta_0':>9}"
          f"{'quiet@maxprior':>16}{'1 feature@med':>15}")

    variants = []
    for w in WEIGHTS:
        c = dataclasses.replace(
            cfg, detector=dataclasses.replace(cfg.detector, weights=w))
        try:
            sc = calibrate_score(c, topo, phi, e_floor)
        except RuntimeError as exc:
            print(f"  {str(w):>22}  infeasible: {exc}")
            continue
        print(f"  {str(tuple(round(x, 2) for x in w)):>22}{sc['lam_s']:>8.1f}"
              f"{sc['theta_0']:>9.4f}{sc['check']['quiet_max_prior']:>16.3f}"
              f"{sc['check']['one_feature_med_prior']:>15.3f}")
        wl = [round(float(x), 6) for x in w]
        variants.append({"detector.weights": wl, "detector.lam_s": sc["lam_s"],
                         "detector.theta_0": sc["theta_0"], "policy.type": "B0"})
        variants.append({"detector.weights": wl, "policy.type": "B0"})

    doc = {"base": BASE,
           "detector": {"ablation": True, "use_prior": False},
           "output_dir": "results/raw",
           "variants": variants,
           "axes": {"attack.profile": ["P", "G", "L", "E"], "seed_attack": SEEDS}}
    header = ("# Phase 8 - sensitivity of the result to the detector weights.\n"
              "#\n# GENERATED by scripts/make_phase8.py - edit that, not this.\n"
              "# Every weight point appears twice: with (lam_s, theta_0) re-solved\n"
              "# for that weighting, and at the phase 1 defaults.  Comparing the two\n"
              "# separates weight sensitivity from threshold sensitivity.\n"
              "#\n#   python -m sim.sweep --sweep " + OUT + " --no-assert\n")
    pathlib.Path(OUT).write_text(
        header + yaml.safe_dump(doc, sort_keys=False, default_flow_style=None,
                                width=100), encoding="utf-8")
    print(f"\nwrote {OUT}: {len(variants)} x {4 * len(SEEDS)} = "
          f"{len(variants) * 4 * len(SEEDS)} runs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
