"""Generate the attacker-defender sweep: every policy against every intensity.

    python scripts/make_minimax.py

Why this exists.  The quiet-attacker slice compares the policies at one chosen
intensity, and the intensity was chosen by the person writing the paper.  That
is exactly the objection a referee should raise: pick the level where the binary
policy happens to fail and the graded one wins by construction.

The fix is to stop choosing.  The attacker also optimises: for each policy it
picks the intensity that maximises the damage it gets through.  Comparing

    max_gamma  D_eff_relay(policy, gamma)

across policies is a minimax comparison - each defence is judged at its own worst
case, nobody chooses the operating point, and the claim strengthens from "B3 wins
at this intensity" to "B3 has the better worst case".

Loud is not automatically better for the attacker and quiet is not either, which
is the whole point: loud gets detected and throttled, quiet gets through but
steals less.  The maximum sits somewhere in between and its location is
policy-dependent - that is the object this sweep measures.
"""
from __future__ import annotations

import pathlib
import sys

import yaml

OUT = "config/sweep_minimax.yaml"
SEEDS = list(range(3, 3 + 20 * 10, 10))

# Each profile's own intensity knob, from "barely there" up to the spec value.
#
# Profile E has TWO, and they are not independent: one physical tap raises the
# QBER of the link it sits on *and* costs it secret key rate, so a configuration
# with a small ``q`` and the full ``s`` is not a quieter attacker, it is an
# attacker that is invisible in one observable and loud in the other.  The pairs
# below are the ones config/sweep_intensity.yaml uses, so the two sweeps describe
# the same adversary.  Leaving ``s`` at the spec while sweeping ``q`` made the E
# row of the first minimax table non-monotone, which is how this was found.
GRID = {
    "G": [("attack.gamma", g) for g in (0.05, 0.10, 0.30, 0.60, 1.00)],
    "L": [("attack.delta", d) for d in (0.02, 0.05, 0.10, 0.25, 0.50)],
    "E": [(("attack.q", q), ("attack.s", s)) for q, s in
          ((0.002, 0.02), (0.005, 0.05), (0.010, 0.10),
           (0.020, 0.17), (0.030, 0.25))],
}

# B0 twice: attacked (the DRR denominator) and clean (the PSI reference).  Both
# are needed at every intensity or the baseline join silently drops the cell.
POLICIES = [
    {"policy.type": "B0", "attack.enabled": True},
    {"policy.type": "B0", "attack.enabled": False},
    {"policy.type": "B1", "policy.tau": 0.5},
    {"policy.type": "B2", "policy.m_paths": 2},
    {"policy.type": "B3", "policy.S_iso": 0.5, "policy.rho_start": 0.1316,
     "policy.kappa": 0.0},
    {"policy.type": "B4"},
    {"policy.type": "BT", "policy.rho_blind": 0.9},
]


def main() -> int:
    variants = []
    for prof, levels in GRID.items():
        for lvl in levels:
            knobs = dict([lvl] if isinstance(lvl[0], str) else lvl)
            for pol in POLICIES:
                variants.append({"attack.profile": prof, **knobs, **pol})
    doc = {"base": "config/attack_t3_otp.yaml",
           "detector": {"ablation": False},
           "output_dir": "results/raw",
           "variants": variants,
           "axes": {"seed_attack": SEEDS}}
    header = (
        "# Attacker-defender: every policy against every attack intensity.\n"
        "#\n# GENERATED by scripts/make_minimax.py - edit that, not this.\n"
        "# Reported as max over intensity per policy, so the comparison is each\n"
        "# defence at its own worst case and nobody picks the operating point.\n"
        "#\n#   python -m sim.sweep --sweep " + OUT + " --no-assert\n")
    pathlib.Path(OUT).write_text(
        header + yaml.safe_dump(doc, sort_keys=False, default_flow_style=None,
                                width=100), encoding="utf-8")
    print(f"wrote {OUT}: {len(variants)} x {len(SEEDS)} = "
          f"{len(variants) * len(SEEDS)} runs "
          f"({len(GRID)} profiles x 5 intensities x {len(POLICIES)} policies)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
